### PR TITLE
Fix AutoYaST schema

### PR DESCRIPTION
**Pull request by imobach**
`printer` section is not included in AutoYaST scheme. It looks like the `AutoInstSchema` declaration is missing.

### CODE REVIEW

**Comment by imobach** [comment]
I've found two additional issues here. I'll fix them again and I'll remove the `[do not merge]` label.

**Comment by imobach** [comment]
@mvidner I've added two missing sections to this schema (taking all the possible values from the manpages). Now it validates the profile given by the customer. Specially the `server_settings` looks repetitive to me so I guess I could do something like: 

```
cups_listentry = element cups_listentry { LIST, element listentry { text }* }

server_settings =
  element server_settings { 
    element AccessLog { cups_listentry }? &
    element Allow { cups_listentry }? &
...
```

Or maybe there's a better way to do that. Any hint?

**Comment by mvidner** [comment]
Yes, except the part with `element cups_listentry` is wrong as that would introduce an actual XML tag. This should work instead:

```
cups_listentries = LIST, element listentry { text }*

server_settings =
  element server_settings { 
    element AccessLog    { cups_listentries }? &
    element Allow        { cups_listentries }? &
...
```

**Comment by imobach** [comment]
@mvidner Oh, I see. I've submitted an updated version. Thanks!

**Comment by mvidner** [comment]
Thank you, LGTM.

**Comment by imobach** [comment]
Thank you for the reviews! Merging...

**Pull request merged**
